language: java
dist: trusty
cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
after_success:
  - mvn clean cobertura:cobertura coveralls:report
